# Generated by Django 5.0.4 on 2024-06-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_studentlevel_studentleveltype_complaint_solved_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
