# Generated by Django 5.0.4 on 2024-06-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_complaint_solved_at_complaint_solved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.studentlevel'),
        ),
    ]
