# Generated by Django 5.0.4 on 2024-06-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_studentlevel_alter_complaint_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentlevel',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_level_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.studentleveltype'),
        ),
    ]
